### PR TITLE
Added Audio Manager script

### PR DESCRIPTION
**Pull request by YourGirlCeleste**
added script to change volume

### CODE REVIEW

**Review by mthomati — COMMENTED** [review]
Add comments to the script explaining what each line is doing. Also clean up with the spacing within the file.

**Comment by YourGirlCeleste** [comment]
Okay, the requested changes have been made.

**Comment by mthomati** [comment]
Great updates to the file.  Upload another script for the same contents in that python script, but written in C#.  You can try to use ChatGPT to see if it can convert or translate that script to C# with a .cs extension.  Upload that file so we can review before merging.  Thanks!

**Comment by YourGirlCeleste** [comment]
The new audio script file has been uploaded.

**Comment by mthomati** [comment]
Everything looks great. Merging into main branch now.

**Pull request merged**
